name: rsp_web
description: RSP Web

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_web3: 2.1.9
  formz: 0.4.1
  get_it: 7.2.0
  injectable: 2.1.0

dev_dependencies:
  build_runner: 2.2.1
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: 2.2.2
  injectable_generator: 2.1.4
  lint_rules:
    path: package/lint_rules


flutter:
  uses-material-design: true
